locals{
    name        = coalesce(lower(var.name),"autogenerated-svacc-name")
    description = coalesce(var.description,"Terraform-managed service account")
}

resource "google_service_account" "default"{
    project      = var.project_id
    account_id   = local.name
    display_name = local.description
}

resource "google_service_account_iam_member" "admin-account-iam"{
    for_each = var.gke_workload_identity_sa

    service_account_id  = google_service_account.default.name
    role                = "roles/iam.workloadIdentityUser"
    member              = "serviceAccount:${each.key}"
}