name: Terraform Apply

on: [push]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/terraform-github-actions@v20
        with:
          terraform_version: ">= 1.0"

      - name: Authenticate to Google Cloud
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > gcp_credentials.json
          export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcp_credentials.json

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
        if: github.ref == 'refs/heads/main' # Or your main branch